server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/$\{segment}
            - name: AuthorizationHeaderFilter
              args: { }
        - id: event-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/events/**
          filters:
            - name: AuthorizationHeaderFilter
              args: { }
      default-filters: []

jwt:
  secret:
    key: V293ci1TdG9yKS1TZWNyZXQtS2V5LVRlc3QxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwCg==
  access-token-expiration: 3600000
